# YOLOv8 Training Configuration

# Model
model: yolov8n.pt # pretrained model
task: detect

# Dataset
data: aws_dataset.yaml  # dataset configuration
nc: 23  # number of classes

# Training
epochs: 100
batch: 16
imgsz: 640
device: 0  # GPU device
workers: 8

# Optimization
optimizer: AdamW
lr0: 0.001
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0

# Validation
val: true
save_period: 10
patience: 50
save_best: true

# Export
format: [pt, onnx]