name: Streamlit CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-streamlit:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 mypy pytest
      
      - name: Lint with flake8
        run: |
          flake8 .
      
      - name: Type check with mypy
        run: |
          mypy .

      - name: Run tests with pytest
        run: |
          pytest

      - name: Streamlit file check
        run: |
          streamlit run test_app.py --server.headless true &
          sleep 5
